name: Integration

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Integration:
    name: Integration

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16.15.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        pnpm: [7.30.3]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm 7
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: Setup Node.js (${{ matrix.node }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
